apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape worker nodes (node-exporter)
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node  # Auto-discovers all nodes
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):.*'
            target_label: __address__
            replacement: '${1}:9100'  # Redirect to node-exporter port
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      # Scrape control plane components (kube-apiserver, etc.)
      - job_name: 'kubernetes-control-plane'
        scheme: https
        tls_config:
          insecure_skip_verify: true  # For homelab only
        static_configs:
          - targets:
            - 'k8s-control-node-1:6443'  # Replace with your control node IPs/hostnames
            - 'k8s-control-node-2:6443'
        metrics_path: /metrics
