apiVersion: v1
kind: Service
metadata:
  name: command-fr-svc
  namespace: command
spec:
  selector:
    app: command-fr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
