# nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {


      server {
        listen 443 ssl;
        server_name command.dulc3.tech;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location / {
          proxy_pass http://command-fr-svc.command.svc.cluster.local:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
      #
      # server {
      #   listen 443 ssl;
      #   server_name grafana.dulc3.tech;
      #
      #   ssl_certificate /etc/nginx/certs/tls.crt;
      #   ssl_certificate_key /etc/nginx/certs/tls.key;
      #
      #   location / {
      #     proxy_pass http://grafana.monitoring.svc.cluster.local:3000;
      #     proxy_set_header Host $host;
      #     proxy_set_header X-Real-IP $remote_addr;
      #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #     proxy_set_header X-Forwarded-Proto $scheme;
      #   }
      # }
      #
      # server {
      #   listen 443 ssl;
      #   server_name prometheus.dulc3.tech;
      #
      #   ssl_certificate /etc/nginx/certs/tls.crt;
      #   ssl_certificate_key /etc/nginx/certs/tls.key;
      #
      #   location / {
      #     proxy_pass http://prometheus.monitoring.svc.cluster.local:9090;
      #     proxy_set_header Host $host;
      #     proxy_set_header X-Real-IP $remote_addr;
      #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #     proxy_set_header X-Forwarded-Proto $scheme;
      #   }
      # }
      #
    }
