# nginx-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 443
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
              #subPath: nginx.conf
            - name: tls
              mountPath: /etc/nginx/certs
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: tls
          secret:
            secretName: pgadmin-tls
