# nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-pgadmin
data:
  nginx.conf: |
    events {}

    http {

      server {
        listen 443 ssl;
        server_name pgadmin.dulc3.tech;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location / {
          proxy_pass http://pgadmin-service.default.svc.cluster.local:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }



      server {
        listen 443;
        server_name pihole.dulc3.tech;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
          rewrite ^/$ /admin/ break;
          proxy_pass http://192.168.4.115;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          # Handle trailing slashes properly
          #proxy_redirect off;
        }
      }

    }
