apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-be
  namespace: command
  labels:
    app: command-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-be
  template:
    metadata:
      labels:
        app: command-be
    spec:
      containers:
        - name: command-be
          image: cyber-command-be:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
