apiVersion: v1
kind: Service
metadata:
  name: command-de-svc
  namespace: command
spec:
  type: ClusterIP
  selector:
    app: command-de
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
